version: '3'
services:
  django:
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    volumes:
      - /mnt/D/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/data/static
    depends_on:
      - django
    ports:
      - '80:80'
