version: '3'
services:
  django:
    build:
      context: .
    expose:
      - '8000'
    depends_on:
      - postgres
    volumes:
      - static_volume:/opt/app/static
  postgres:
    image: postgres:13
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./service.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/data/static
    depends_on:
      - django
    ports:
      - '80:80'
volumes:
  postgres_volume:
    driver: local
    driver_opts:
      type: 'none'
      o: "bind"
      device: ${DB_LOCAL_PATH}
  static_volume:
