version: '3'
services:
  django:
    build:
      context: .
    ports:
      - '8000:8000'
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    volumes:
      - /mnt/D/postgresql/data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_DB=${DB_NAME}
